name: BananaGL CI

on:
  push:
    branches: [ main, dev ]

jobs:
  run-settings:
    runs-on: ubuntu-latest
    outputs:
      out-bump: ${{ steps.run.outputs.bump }}
      out-package: ${{ steps.run.outputs.package }}
      out-deploy: ${{ steps.run.outputs.deploy }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Check for commit tags
      id: run
      run: |
        log=$(git log --pretty=oneline --max-count=1)
        case "$log" in
            *action::bump* ) bump=1;;
            * ) bump=0;;
        esac
        echo "::set-output name=bump::$bump"

        case "$log" in
            *action::package* ) package=1;;
            * ) package=0;;
        esac
        echo "::set-output name=package::$package"

        case "$log" in
            *action::deploy* ) deploy=1;;
            * ) deploy=0;;
        esac
        echo "::set-output name=deploy::$deploy"









